#!/usr/bin/env bash

#  ██╗   ██╗ ██████╗ ██╗     ██╗   ██╗███╗   ███╗███████╗
#  ██║   ██║██╔═══██╗██║     ██║   ██║████╗ ████║██╔════╝
#  ██║   ██║██║   ██║██║     ██║   ██║██╔████╔██║█████╗  
#  ╚██╗ ██╔╝██║   ██║██║     ██║   ██║██║╚██╔╝██║██╔══╝  
#   ╚████╔╝ ╚██████╔╝███████╗╚██████╔╝██║ ╚═╝ ██║███████╗
#    ╚═══╝   ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝
#	gh0stzk
#	https://github.com/gh0stzk/dotfiles
#	Script to control the eww bar in z0mbi3 rice
#	23.09.2023 12:30:34

get_vol () {
  volumen=$(amixer -D pulse get Master | grep -o '[0-9]*%' | sed 's/%//' | head -1)
  [[ $volumen == 'muted' ]] && echo "0" || echo "${volumen}"
}

get_icon () {
  local vol=$(get_vol)
  echo "images/$( [[ $vol == "0" ]] && echo "mute" || echo "volume" ).png"
}

case "$1" in
  --vol) get_vol;;
  --icon) get_icon;;
  --toggle-muted) amixer -D pulse set Master toggle;;
esac
