#!/usr/bin/env bash
#  ██╗   ██╗ ██████╗ ██╗     ██╗   ██╗███╗   ███╗███████╗
#  ██║   ██║██╔═══██╗██║     ██║   ██║████╗ ████║██╔════╝
#  ██║   ██║██║   ██║██║     ██║   ██║██╔████╔██║█████╗  
#  ╚██╗ ██╔╝██║   ██║██║     ██║   ██║██║╚██╔╝██║██╔══╝  
#   ╚████╔╝ ╚██████╔╝███████╗╚██████╔╝██║ ╚═╝ ██║███████╗
#    ╚═══╝   ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝
#
#	gh0stzk
#	https://github.com/gh0stzk/dotfiles
#	This script controls the volume of your system, using amixer.
#	23.09.2023 09:30:24
#

# Icons
vol_dir="$HOME/.config/bspwm/assets"
notify_cmd='dunstify -u low -h string:x-dunst-stack-tag:cvolum'

# Get Volume
get_volume() {
	amixer -D pulse get Master | grep -m 1 -oP '[0-9]+(?=%)'
}

# Get icons
get_icon() {
	if [[ $(amixer -D pulse get Master | grep '\[off\]') ]]; then
		icon="$vol_dir/mute.png"
	else
		icon="$vol_dir/vol.png"
	fi
}

# Get icons Microphone
get_icon_mic() {
	if [[ $(amixer -D pulse get Capture | grep '\[off\]') ]]; then
		icon="$vol_dir/mic_muted.png"
	else
		icon="$vol_dir/mic_cap.png"
	fi
}

# Notify
notify_user() {
	${notify_cmd} -i "$icon" "Volume : $(get_volume)%"
}

# Adjust Volume
adjust_volume() {
	[[ $(amixer -D pulse get Master | grep '\[off\]') ]] && amixer -D pulse set Master unmute
	amixer -D pulse sset Master "$1" && get_icon && notify_user
}

# Toggle Mute
toggle_mute() {
	if [[ $(amixer -D pulse get Master | grep '\[off\]') ]]; then
		amixer -D pulse set Master unmute
		get_icon
		message="Unmute"
	else
		amixer -D pulse set Master mute
		get_icon
		message="Mute"
	fi
	${notify_cmd} -i "$icon" "$message"
}

# Toggle Mute Microphone
toggle_mute_mic() {
	if [[ $(amixer -D pulse get Capture | grep '\[off\]') ]]; then
		amixer -D pulse set Capture cap
		get_icon_mic
		message="Cap"
	else
		amixer -D pulse set Capture nocap
		get_icon_mic
		message="Nocap"
	fi
	${notify_cmd} -i "$icon" "$message"
}

# Execute accordingly
case "$1" in
	--get) get_volume ;;
	--inc) adjust_volume 5%+ ;;
	--dec) adjust_volume 5%- ;;
	--toggle) toggle_mute ;;
	--toggle_mic) toggle_mute_mic ;;
	*) echo "$(get_volume)%" ;;
esac
